version: "3"
services:
  reverseproxy:
    build:
      context: udagram-reverse-proxy
    image: imeggi/udagram-reverse-proxy 
  backend_user:
    build:
      context: udagram-restapi-user
    image: imeggi/udagram-restapi-user
  backend_feed:
    build:
      context: udagram-restapi-feed 
    image: imeggi/udagram-restapi-feed
  frontend:
    build:
      context: udagram-frontend 
    image: imeggi/udagram-frontend:latest