version: "3"
services:
 reverseproxy:
 build:
 context: .
 image: imeggi/reverseproxy 
 backend_user:
 build:
 context: udacity-c3-restapi-user
 image: imeggi/udacity-restapi-user
 backend_feed:
 build:
 context: udacity-c3-restapi-feed 
 image: imeggi/udacity-restapi-feed
 frontend:
 build:
 context: udacity-c3-frontend 
 image: imegi/udacity-frontend:local